#!/usr/bin/env bash

echo "This is a destructive operation. Press Ctrl+c now if you're unsure it's OK to continue, or press Enter if you know what you're doing"
read -r

_store="${HOME}/.passveil"
if [[ -n "$1" ]]; then
  _store="$1"
fi

# passveil --store "$_store" undo

_repo="${_store}/store"
cd "$_repo" || (echo "${_repo} not found" ; exit 228)
darcs status | cut -d\  -f2 | parallel 'rm -rvf "{1}"'
darcs record -a -m "unfuckup"
darcs obliterate --no-cache --not-in-remote
